GET http://localhost:8080/jsf/api/products/2
Accept: application/json
###

GET http://localhost:8080/jsf/api/products
Accept: application/json

###
GET http://localhost:8080/jsf/api/products/404
Accept: application/json

###
POST http://localhost:8080/jsf/api/products
Content-Type: application/json

{
  "categoryId": "1",
  "name": "super new",
  "price": 200
}

###
POST http://localhost:8080/jsf/api/products
Content-Type: application/json

{
  "categoryId": "6",
  "name": "dress",
  "price": 2000
}
###
PUT http://localhost:8080/jsf/api/products
Content-Type: application/json

{
  "id": "2",
  "name": "doll",
  "price": 250,
  "categoryId": 1
}

###
GET http://localhost:8080/jsf/api/products/getByName?name=dress
Accept: application/json

###

GET http://localhost:8080/jsf/api/products/getByCategoryId/1
Accept: application/json

###
DELETE http://localhost:8080/jsf/api/products/404

###
DELETE http://localhost:8080/jsf/api/products/1

###
GET http://localhost:8080/jsf/api/categories
Accept: application/json

###
POST http://localhost:8080/jsf/api/categories
Content-Type: application/json

{
  "name": "clothes"
}

###


